### ISSUE TITLE
depends on racket-doc

### ISSUE THREAD

**Issue by clacke** [mbutterick/brag#17]
It would be nice to split brag into brag-lib and brag-doc, see stchang/graph#35 for motivation.

I am willing to create the PR.

**Comment by mbutterick** [comment]
Though apparently it’s a little [trickier than it looks](https://github.com/stchang/graph/pull/37)?

**Comment by clacke** [comment]
Is supporting Racket 5 important for brag?

**Comment by mbutterick** [comment]
No, but making my life easy is definitely a design goal of `brag`. I have not followed this package-splitting practice for any of my other packages because it makes more work for me, and it has not presented any practical problems for users of my software. If I’m missing something, I invite correction. Otherwise I will table this issue as falling beneath the cost–benefit threshold.

**Comment by clacke** [comment]
For most users it won't make a difference, but for Nix packaging, basing everything on racket-minimal and making the transitive dependency set as small as possible makes life much easier -- we're talking build time differences on the scale of half an hour when everything is newly bumped and no dependencies have been cached yet.

How about I make the PR providing the split, and you can look at it and see how high the maintenance burden looks? If you don't like it, I'll use plan B and synthesize a brag-lib in racket2nix instead.

**Comment by mbutterick** [comment]
OK, this is done, but could you please test it to make sure it works the way you expect.

**Comment by clacke** [comment]
Cool, thanks! Will have a look.

**Comment by clacke** [comment]
It's excellent. Thank you!
